import { AsciiConfig, PostProcessingConfig, AnimationEffectsConfig } from '../types';
import {
  DEFAULT_CHARS,
  DENSE_CHARS,
  BLOCKS_CHARS,
  KATAKANA_CHARS,
  CROSSES_CHARS,
  DOTS_CHARS,
} from './asciiUtils';

/**
 * A style preset is a complete render configuration that users can
 * apply with one click. Each preset overrides all config values.
 */
export interface StylePreset {
  id: string;
  name: string;
  description: string;
  config: Partial<AsciiConfig>;
}

const noPostProcessing: PostProcessingConfig = {
  scanlines: 0,
  glow: 0,
  chromaticAberration: 0,
  noise: 0,
  vignette: 0,
  flicker: 0,
};

const noAnimationEffects: AnimationEffectsConfig = {
  matrixRain: 0,
  waveDistortion: 0,
  typingReveal: false,
};

export const STYLE_PRESETS: StylePreset[] = [
  // ─── CLEAN ────────────────────────────────────────────
  {
    id: 'default',
    name: 'Default',
    description: 'Clean ASCII with standard characters',
    config: {
      resolution: 60,
      chars: DEFAULT_CHARS,
      color: '#ffffff',
      backgroundColor: '#000000',
      invert: true,
      fontAspectRatio: 0.55,
      overlayOpacity: 0,
      useSourceColor: false,
      brightness: 0,
      contrast: 0,
      saturation: 0,
      dithering: false,
      sharpness: 50,
      colorPalette: 'none',
      postProcessing: { ...noPostProcessing },
      animationEffects: { ...noAnimationEffects },
    },
  },

  // ─── RETRO MONITORS ──────────────────────────────────
  {
    id: 'crt-terminal',
    name: 'CRT Terminal',
    description: 'Green phosphor monitor with scanlines and glow',
    config: {
      resolution: 80,
      chars: DEFAULT_CHARS,
      color: '#33ff33',
      backgroundColor: '#0a0a0a',
      invert: true,
      fontAspectRatio: 0.55,
      overlayOpacity: 0,
      useSourceColor: false,
      brightness: 10,
      contrast: 30,
      saturation: 0,
      dithering: false,
      sharpness: 80,
      colorPalette: 'none',
      postProcessing: {
        scanlines: 120,
        glow: 50,
        chromaticAberration: 0,
        noise: 20,
        vignette: 60,
        flicker: 15,
      },
      animationEffects: { ...noAnimationEffects },
    },
  },
  {
    id: 'retro-amber',
    name: 'Retro Amber',
    description: 'Warm amber CRT with vignette and noise',
    config: {
      resolution: 60,
      chars: DEFAULT_CHARS,
      color: '#ffb000',
      backgroundColor: '#1a0e00',
      invert: true,
      fontAspectRatio: 0.55,
      overlayOpacity: 0,
      useSourceColor: false,
      brightness: 0,
      contrast: 20,
      saturation: 0,
      dithering: false,
      sharpness: 50,
      colorPalette: 'none',
      postProcessing: {
        scanlines: 80,
        glow: 50,
        chromaticAberration: 0,
        noise: 30,
        vignette: 80,
        flicker: 10,
      },
      animationEffects: { ...noAnimationEffects },
    },
  },

  // ─── DIGITAL / SCI-FI ────────────────────────────────
  {
    id: 'matrix',
    name: 'Matrix',
    description: 'Digital rain cascade with katakana characters',
    config: {
      resolution: 90,
      chars: KATAKANA_CHARS,
      color: '#00ff41',
      backgroundColor: '#000000',
      invert: true,
      fontAspectRatio: 0.55,
      overlayOpacity: 0,
      useSourceColor: false,
      brightness: -20,
      contrast: 60,
      saturation: 0,
      dithering: false,
      sharpness: 100,
      colorPalette: 'none',
      postProcessing: {
        scanlines: 40,
        glow: 60,
        chromaticAberration: 15,
        noise: 10,
        vignette: 40,
        flicker: 5,
      },
      animationEffects: {
        matrixRain: 150,
        waveDistortion: 0,
        typingReveal: false,
      },
    },
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    description: 'Hot pink glitch city — dense characters, hard edges',
    config: {
      resolution: 90,
      chars: DENSE_CHARS,
      color: '#ff2a6d',
      backgroundColor: '#000000',
      invert: true,
      fontAspectRatio: 0.55,
      overlayOpacity: 0,
      useSourceColor: false,
      brightness: 0,
      contrast: 80,
      saturation: 0,
      dithering: false,
      sharpness: 120,
      colorPalette: 'none',
      postProcessing: {
        scanlines: 60,
        glow: 40,
        chromaticAberration: 50,
        noise: 15,
        vignette: 50,
        flicker: 8,
      },
      animationEffects: { ...noAnimationEffects },
    },
  },

  // ─── COLOR ────────────────────────────────────────────
  {
    id: 'neon',
    name: 'Neon',
    description: 'Vivid source colors with chromatic aberration and glow',
    config: {
      resolution: 80,
      chars: DEFAULT_CHARS,
      color: '#ffffff',
      backgroundColor: '#000000',
      invert: true,
      fontAspectRatio: 0.55,
      overlayOpacity: 0,
      useSourceColor: true,
      brightness: 20,
      contrast: 50,
      saturation: 80,
      dithering: false,
      sharpness: 60,
      colorPalette: 'none',
      postProcessing: {
        scanlines: 30,
        glow: 70,
        chromaticAberration: 40,
        noise: 5,
        vignette: 30,
        flicker: 0,
      },
      animationEffects: { ...noAnimationEffects },
    },
  },
  {
    id: 'color-photo',
    name: 'Color Photo',
    description: 'Source colors with block characters for photo-like output',
    config: {
      resolution: 120,
      chars: BLOCKS_CHARS,
      color: '#ffffff',
      backgroundColor: '#000000',
      invert: true,
      fontAspectRatio: 0.55,
      overlayOpacity: 0,
      useSourceColor: true,
      brightness: 10,
      contrast: 20,
      saturation: 20,
      dithering: false,
      sharpness: 80,
      colorPalette: 'none',
      postProcessing: { ...noPostProcessing },
      animationEffects: { ...noAnimationEffects },
    },
  },
  {
    id: 'synthwave',
    name: 'Synthwave',
    description: 'Retro-futuristic palette with purple haze and glow',
    config: {
      resolution: 70,
      chars: DEFAULT_CHARS,
      color: '#ffffff',
      backgroundColor: '#0a0010',
      invert: true,
      fontAspectRatio: 0.55,
      overlayOpacity: 0,
      useSourceColor: true,
      brightness: 10,
      contrast: 40,
      saturation: 60,
      dithering: false,
      sharpness: 50,
      colorPalette: 'synthwave',
      postProcessing: {
        scanlines: 20,
        glow: 60,
        chromaticAberration: 20,
        noise: 5,
        vignette: 70,
        flicker: 0,
      },
      animationEffects: { ...noAnimationEffects },
    },
  },
  {
    id: 'gameboy',
    name: 'Gameboy',
    description: 'Authentic 4-color green palette with dithering',
    config: {
      resolution: 40,
      chars: BLOCKS_CHARS,
      color: '#9bbc0f',
      backgroundColor: '#0f380f',
      invert: true,
      fontAspectRatio: 0.55,
      overlayOpacity: 0,
      useSourceColor: true,
      brightness: 0,
      contrast: 10,
      saturation: 0,
      dithering: true,
      sharpness: 0,
      colorPalette: 'gameboy',
      postProcessing: { ...noPostProcessing },
      animationEffects: { ...noAnimationEffects },
    },
  },

  // ─── ARTISTIC ─────────────────────────────────────────
  {
    id: 'noir',
    name: 'Noir',
    description: 'Dramatic film noir with crushing shadows and vignette',
    config: {
      resolution: 70,
      chars: DENSE_CHARS,
      color: '#e0e0e0',
      backgroundColor: '#000000',
      invert: true,
      fontAspectRatio: 0.55,
      overlayOpacity: 0,
      useSourceColor: false,
      brightness: -10,
      contrast: 150,
      saturation: 0,
      dithering: false,
      sharpness: 100,
      colorPalette: 'none',
      postProcessing: {
        scanlines: 0,
        glow: 0,
        chromaticAberration: 0,
        noise: 10,
        vignette: 100,
        flicker: 0,
      },
      animationEffects: { ...noAnimationEffects },
    },
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    description: 'Engineering schematic — white on deep navy',
    config: {
      resolution: 80,
      chars: CROSSES_CHARS,
      color: '#b8d4e3',
      backgroundColor: '#0d1b2a',
      invert: true,
      fontAspectRatio: 0.55,
      overlayOpacity: 0,
      useSourceColor: false,
      brightness: 0,
      contrast: 40,
      saturation: 0,
      dithering: false,
      sharpness: 80,
      colorPalette: 'none',
      postProcessing: {
        scanlines: 0,
        glow: 20,
        chromaticAberration: 0,
        noise: 8,
        vignette: 40,
        flicker: 0,
      },
      animationEffects: { ...noAnimationEffects },
    },
  },
  {
    id: 'typewriter',
    name: 'Typewriter',
    description: 'Sepia ink on warm paper — mechanical and analog',
    config: {
      resolution: 50,
      chars: DEFAULT_CHARS,
      color: '#3b2f1e',
      backgroundColor: '#f5f0e6',
      invert: false,
      fontAspectRatio: 0.55,
      overlayOpacity: 0,
      useSourceColor: false,
      brightness: 10,
      contrast: 30,
      saturation: 0,
      dithering: false,
      sharpness: 40,
      colorPalette: 'none',
      postProcessing: {
        scanlines: 0,
        glow: 0,
        chromaticAberration: 0,
        noise: 25,
        vignette: 30,
        flicker: 0,
      },
      animationEffects: { ...noAnimationEffects },
    },
  },
];
